[package]
name = "i-client"
version = "0.1.0"
authors = ["shumy <micaelpedrosa@gmail.com>"]
edition = "2018"

[dependencies]
core-fpi = { version = "0.1", path = "../core-fpi" }
clap = "2.33"
reqwest = "0.9"
base64 = "0.10"