#!/bin/bash
cargo build --release;
trap 'kill %1; kill %2; kill %3' SIGINT;
./target/release/f-node -h ./test-net/node0 &
./target/release/f-node -h ./test-net/node1 &
./target/release/f-node -h ./test-net/node2 &
./target/release/f-node -h ./test-net/node3;