[package]
name = "crypto-fpi"
version = "0.1.0"
authors = ["shumy <micaelpedrosa@gmail.com>"]
edition = "2018"

[lib]
name = "crypto_fpi"

[dependencies]
curve25519-dalek = "^1"
sha2 = "^0.8"
rand_os = "^0.1"